### PR TITLE
LIQO home view - general cluster status view

### PR DESCRIPTION
**Pull request by nappozord**
# Description

This PR introduces a view that shows the general status of the cluster.

In details (every metric is updated every 30 seconds):

- CPU and RAM real time consumption (in %) for the Home cluster and trend consumption (represented with a line chart). Various foreign clusters are represented with a different color, and how many resources are using. (Hovering with the mouse over a section of the chart will show who is using how much. The resources used by you are colored blue)
- CPU and RAM real time consumption (in %) for the Foreign clusters and trend consumption (represented with a line chart). This is the sum of all the foreign clusters' metrics, and different sections of the chart represent different clusters where you are offloading your pods. It is useful to show how much of the total shared resources you are using.

image

### CODE REVIEW

**Comment by frisso** [comment]
First, this is really great!
Some suggestions.
1) We may be peered to multiple clusters. So, the "foreign resources" section can be duplicated multiple times.
2) We may have multiple peers consuming our resources. It would be nice to show this consumption, e.g., using different colors, in the view related to the "home" cluster.

**Comment by nappozord** [comment]
> 1. We may be peered to multiple clusters. So, the "foreign resources" section can be duplicated multiple times.
> 2. We may have multiple peers consuming our resources. It would be nice to show this consumption, e.g., using different colors, in the view related to the "home" cluster.

The status (CPU%, RAM%) of a single connection is showed in the "Details" menu of said connection (under tabs foreign and/or home) (#25 ). This view is intended to be a more generic exposure of the consuming and consumed resources.

**Comment by nappozord** [comment]
ref. #19

**Review by palexster — APPROVED** [review]
/approve

**Pull request closed without merging**
